name: RegrowthPinata
version: ${project.version}
main: org.lushplugins.pinata.RegrowthPinata
api-version: '1.13'
author: "bentahsin, RegrowthMC"
softdepend:
  - TitleManager
  - ProtocolLib
  - PlaceholderAPI
  - DecentHolograms